"""Add movie models

Revision ID: 0ef258827b9f
Revises: e03e75026048
Create Date: 2024-10-14 21:53:32.380831

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel as sa


# revision identifiers, used by Alembic.
revision: str = '0ef258827b9f'
down_revision: Union[str, None] = 'e03e75026048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sa.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
